name: CI with Ceedling

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Add Gem Directory to PATH
      run: echo "${HOME}/.local/share/gem/ruby/3.0.0/bin" >> $GITHUB_PATH
    - name: Install Dependencies
      run: bundle install

    - name: Run Ceedling
      run: ceedling test:all



    # - name: check version
    #   run: |
    #     ceedling --version 
